name: main

on:
  push:
    paths:
      - 'mingw-w64-*/*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { msystem: mingw32, toolchain: i686 },
          { msystem: mingw64, toolchain: x86_64 }
        ]
      fail-fast: false
    defaults:
      run:
        shell: msys2 {0}
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: git
          update: true

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 3.6

      - name: CI-Build
        run: ./ci-build.sh
        env:
          BUILD_URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          MINGW_ARCH: ${{ matrix.msystem }}
          MINGW_TOOLCHAIN: ${{ matrix.toolchain }}
          PACMAN_REPOSITORY: ${{ matrix.msystem }}-backports

      - name: "Upload binary package"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.msystem }}-backports
          path: artifacts/

  deploy:
    name: Deploy to staging server
    runs-on: ubuntu-20.04
    needs: [build]
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Get artifacts for deployment
        uses: actions/download-artifact@v3
      - id: deployment
        name: Uploading files
        run: |
          ls -ltrR
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          echo "${STAGINGKEY}" > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
          echo 'put -pr .' | sftp "${STAGINGUSER}@ftp.opencpu.org:/rtools"
          rm -f ~/.ssh/id_rsa
        env:
          STAGINGUSER: ${{ secrets.STAGINGUSER }}
          STAGINGKEY: ${{ secrets.STAGINGKEY }}
